const EventEmitter = require('events');

const START_QUERY_DATA_EVENT = 'START_QUERY_DATA_EVENT';
const GAME_STOPPED = 'GAME_STOPPED';
const GAME_OVER = 'GAME_OVER';
const CHANGE_DATA_EVENT = 'CHANGE_DATA_EVENT';
const START_MEASURING_INIT_BPM = 'START_MEASURING_INIT_BPM';
const STOP_MEASURING_INIT_BPM = 'STOP_MEASURING_INIT_BPM';
const UPDATE_COUNTDOWN_EVENT = 'UPDATE_COUNTDOWN_EVENT';
const UPDATE_COUNTDOWN_EVENT2 = 'UPDATE_COUNTDOWN_EVENT2';
const INIT_BMP_EVENT = 'INIT_BMP_EVENT';
const WINNER_FOUND_EVENT = 'WINNER_FOUND_EVENT';

class AppEventEmitter extends EventEmitter {}

const appEventEmitter = new AppEventEmitter();

module.exports = {
  appEventEmitter,
  START_QUERY_DATA_EVENT,
  GAME_STOPPED,
  GAME_OVER,
  CHANGE_DATA_EVENT,
  START_MEASURING_INIT_BPM,
  STOP_MEASURING_INIT_BPM,
  UPDATE_COUNTDOWN_EVENT,
  UPDATE_COUNTDOWN_EVENT2,
  INIT_BMP_EVENT,
  WINNER_FOUND_EVENT
};